### PR TITLE
Write timestamps with an explicit UTC offset, and tighten sem:exportedAt to xsd:dateTimeStamp (#1114)

### LINKED ISSUE #1114: [BUG] Every timestamp is written timezone-naive, in two idioms that mean different things, so a timezone-qualified SPARQL filter silently drops them
Filing this as @KaifAhmad1 asked on #1107, where the missing timezone forced the shipped vocabulary to weaken `sem:exportedAt`'s range. It turned out to be wider than the one call site, so the report covers what I could verify through the public API.

## Bug Description

Every timestamp Semantica writes is timezone-naive, in two different idioms that mean two different things and serialize identically:

- `datetime.now().isoformat()` — 106 calls across 41 files, 18 of them in `semantica/export/`, including `json_exporter.py:505` which writes `sem:exportedAt` into a JSON-LD export. This reads the **local** clock of whatever machine ran the export.
- `datetime.utcnow().isoformat()` — 70 calls across 23 files, including `provenance/schemas.py:94`, whose value reaches RDF as `prov:generatedAtTime`, `prov:startedAtTime`, `prov:endedAtTime` and `prov:atTime`, typed `xsd:dateTime` (`provenance/manager.py:1239`, `1283`, `1286`, `1294`). This means **UTC**.

Neither writes an offset, so once the value is in RDF nothing distinguishes them. `2026-08-19T14:19:04` from the PROV-O exporter is 14:19 UTC; the same string from the JSON-LD exporter is 14:19 in an unrecorded local zone, anywhere from 00:19Z to 02:19Z the following day.

`datetime.utcnow()` is also deprecated. On Python 3.13, constructing a `ProvenanceEntry` under `-W error::DeprecationWarning` raises:

```
DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a
future version. Use timezone-aware objects to represent datetimes in UTC:
datetime.datetime.now(datetime.UTC).
```

## Why it matters

**A timezone-qualified SPARQL filter silently excludes every Semantica-written timestamp.** Under XSD 1.1, comparing a value with no timezone against one with a timezone is indeterminate whenever they fall within the ±14-hour window, and SPARQL turns an indeterminate comparison into an error, which `FILTER` discards as a non-match. Loading three exports into Oxigraph — one stamped the way Semantica stamps it, two stamped correctly:

```sparql
SELECT ?e WHERE {
  ?e sem:exportedAt ?t .
  FILTER (?t < "2026-08-19T18:00:00Z"^^xsd:dateTime)
}
```

```
Exports written before 18:00Z, per SPARQL:
    https://example.org/exportB          <- "2026-08-19T15:00:00+05:30"
```

`exportA`, carrying `"2026-08-19T14:19:04"` exactly as `_convert_kg_to_jsonld` writes it, is absent. Not an error, not a warning: the row is dropped. Every "what changed since", "what was exported before the incident", "which provenance activity ran first" query silently omits the records Semantica wrote, and returns a plausible-looking answer.

**The value cannot be tightened to `xsd:dateTimeStamp`.** `xsd:dateTimeStamp` requires an explicit timezone, so the vocabulary in #1109 had to declare the weaker `xsd:dateTime` and say why in the term's own comment. Fixing the stamp lets that range be tightened and lets a SHACL shape enforce it.

**Provenance is the one place this hurts most.** An audit trail whose timestamps cannot be ordered against timestamps from any other system is not much of an audit trail. The PROV-O export is otherwise the cleanest RDF this package produces.

## Steps to Reproduce

```python
from semantica.export.json_exporter import JSONExporter
kg = {"entities": [{"id": "https://example.org/e1", "text": "Bob"}], "relationships": []}
doc = JSONExporter()._convert_kg_to_jsonld(kg)
print(doc["@id"], doc["semantica:exportedAt"])
```

Run it under four timezones, at the same instant:

```
  TZ=UTC                  @id=https://semantica.dev/graph/2026-08-19T14:19:02.821736
                          sem:exportedAt=2026-08-19T14:19:02.821750
  TZ=Europe/London        @id=https://semantica.dev/graph/2026-08-19T15:19:03.169234
                          sem:exportedAt=2026-08-19T15:19:03.169252
  TZ=Asia/Kolkata         @id=https://semantica.dev/graph/2026-08-19T19:49:03.511905
                          sem:exportedAt=2026-08-19T19:49:03.511919
  TZ=America/Los_Angeles  @id=https://semantica.dev/graph/2026-08-19T07:19:03.867247
                          sem:exportedAt=2026-08-19T07:19:03.867268
```

Four exports of one graph at one instant, four timestamps spanning twelve hours, and nothing in the output says which zone any of them is in.

## Actual Behavior

`2026-08-19T14:19:04.229937` — `datetime.fromisoformat(...).tzinfo` is `None`.

## Expected Behavior

`datetime.now(timezone.utc).isoformat()` at every site, which yields `2026-08-19T14:19:04.229937+00:00`: a single unambiguous instant, comparable in SPARQL against any correctly stamped value, and valid `xsd:dateTimeStamp` so the vocabulary can declare the tighter range. `datetime.utcnow()` sites need the same treatment and are on a deprecation clock anyway.

Nothing about the fix is subtle, but there are 176 call sites, so it is worth deciding whether it lands as one mechanical sweep or export-and-provenance first. Happy to take either; say which and I will open the PR.

## A second defect at the same call sites, splittable if you prefer

`_convert_kg_to_jsonld` mints the document node's identity from that same clock (`json_exporter.py:484`, and `413` for the `data/` variant):

```python
"@id": f"https://semantica.dev/graph/{datetime.now().isoformat()}",
```

Two consequences:

1. **The same graph exported twice is two documents.** Two calls, one process, one timezone:
   ```
   https://semantica.dev/graph/2026-08-19T14:19:04.229924
   https://semantica.dev/graph/2026-08-19T14:19:04.598475
   ```
   Nothing joins a re-export to the export it replaces, which is the identity problem #1101 fixed for entities and relationships, still standing for the document node.
2. **Document identity depends on the exporter's timezone**, per the four-timezone run above: the same content on a machine in Kolkata and a machine in Los Angeles produces IRIs twelve hours apart, and two machines sharing a wall clock but not an instant can produce the same IRI for different exports.

Minting it the way #1109 mints entity IRIs — SHA-256 over the graph content, or a caller-supplied id — makes a re-export of unchanged content land on the same node, and leaves the timestamp as a property of the document rather than its name. That is a modelling decision rather than a mechanical fix, so I have left it alone; if you would rather track it separately I will split it out.

## Environment

- **OS**: macOS 15 (Darwin 25.5.0)
- **Python Version**: 3.13.14
- **Semantica Version**: 0.6.5, plus the #1109 branch
- **Installation Method**: source

Verified with rdflib 7.6.0 and pyoxigraph 0.5.9. Related: #1107 (vocabulary range), #1101 (identity minting), #1100 (serializers disagreeing on datatypes).

### PR DESCRIPTION
**Pull request by fabio-rovai**
Closes #1114, the timezone report you asked me to file on #1107.

`semantica/export/` stamped every value with `datetime.now().isoformat()`, which reads the machine's **local** clock. `semantica/provenance/` stamped its own with `datetime.utcnow().isoformat()`, which reads **UTC**. Both return a naive datetime and both serialize identically, so once the value leaves the process nothing distinguishes them: the same string means two different instants depending on which module wrote it.

In RDF the consequence is silent rather than loud. Under XSD 1.1, comparing a value with no timezone against one with a timezone is indeterminate whenever the two fall inside the ±14 hour window; SPARQL turns an indeterminate comparison into an error, and `FILTER` discards errors as non-matches. Three timestamps in an Oxigraph store, one stamped the way Semantica stamped it and two stamped correctly:

```sparql
SELECT ?e WHERE { ?e sem:exportedAt ?t . FILTER (?t < "2026-08-19T18:00:00Z"^^xsd:dateTime) }
```

```
    https://example.org/exportB          <- "2026-08-19T15:00:00+05:30"
```

`exportA`, carrying `"2026-08-19T14:19:04"` exactly as `_convert_kg_to_jsonld` wrote it, is simply absent. `prov:generatedAtTime`, `prov:startedAtTime`, `prov:endedAtTime` and `prov:atTime` all carried values written that way, so an audit trail could not be ordered against timestamps from any other system.

The same export run under four timezones at one instant, before the fix:

```
  TZ=UTC                  sem:exportedAt=2026-08-19T14:19:02.821750
  TZ=Europe/London        sem:exportedAt=2026-08-19T15:19:03.169252
  TZ=Asia/Kolkata         sem:exportedAt=2026-08-19T19:49:03.511919
  TZ=America/Los_Angeles  sem:exportedAt=2026-08-19T07:19:03.867268
```

## What this changes

`utc_now()` and `utc_now_iso()` in `semantica/utils/helpers.py`, exported from `semantica.utils`, used at all 29 call sites in `export/` (`json_exporter`, `yaml_exporter`, `report_generator`, `export_provenance`) and `provenance/` (`manager`, `schemas`, `bridge_axiom`). Values now read `2026-08-19T14:19:04.229937+00:00`.

`sem:exportedAt`'s range in the vocabulary that landed with #1109 tightens from `xsd:dateTime` to `xsd:dateTimeStamp`. The term's comment had to explain why the weaker range was necessary; that reason is gone.

`datetime.utcnow()` is deprecated as of Python 3.12 and scheduled for removal — constructing a `ProvenanceEntry` under `-W error::DeprecationWarning` on 3.13 raised, and no longer does.

## What this deliberately does not change

The other **147** naive call sites, in `context/`, `vector_store/`, `seed/` and elsewhere. Those timestamps are compared against values parsed back from previously stored naive strings (`datetime.fromisoformat(data["timestamp"])` in `context/decision_models.py`, `context/causal_analyzer.py`, `provenance/schemas.py` and 35 other places), so converting the write side alone would raise `TypeError: can't compare offset-naive and offset-aware datetimes` on data written by an earlier version. That sweep needs a read side that treats a missing offset as UTC, and it is a different change with a migration story attached. Happy to take it next if you want it.

One thing worth your eye: `ProvenanceManager.query_recorded_between` compares ISO strings lexicographically. Adding the `+00:00` suffix does not reorder anything, because the comparison diverges long before the offset in every realistic case, but a bound written to match a stored value character-for-character would now sit fractionally below it. Existing behaviour was already lexical on ISO strings, so I have left it alone rather than change the semantics of a query method in a timestamp PR.

## Verification

`tests/export/test_timestamp_timezones.py` and `tests/provenance/test_timestamp_timezones.py`: offset presence on every export and provenance path, PROV-O literals valid as `xsd:dateTimeStamp`, comparison against a timezone-aware instant without `TypeError`, the declared range matching what the exporter writes, the document `@id` still a valid IRI with `+00:00` in it, and the Oxigraph filter that dropped the naive value.

That last test picks a bound one hour ahead rather than a round year, on purpose: a bound years away is determinate even for a naive value, so the version of the test I wrote first passed without the fix. 13 of the 14 tests fail with this commit's `semantica/export`, `semantica/provenance` and vocabulary reverted.

564 export, ontology and provenance tests pass. Across the full suite the failure set is identical before and after — 329 failures either way, all from optional dependencies missing in my environment.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Review by KaifAhmad1 — APPROVED** [review]
Fixes #1114 — every export/provenance timestamp was naive (`datetime.now()` local time in `export/`, `datetime.utcnow()` UTC in `provenance/`, indistinguishable once serialized), so a timezone-qualified SPARQL `FILTER` silently dropped Semantica-written records instead of erroring. Adds `utc_now()`/`utc_now_iso()`, ports all 29 call sites, tightens `sem:exportedAt`'s vocabulary range to `xsd:dateTimeStamp`, and incidentally fixes the Python 3.12 `datetime.utcnow()` deprecation. Second commit fixes a real regression this PR introduced and Qodo caught: `query_recorded_between`/`audit_log` compared timestamps as raw strings, which breaks once some entries carry `+00:00` and others don't — now compares instants via a new `to_utc_datetime()` that reads a missing offset as UTC (correct, since that's what the pre-fix values actually meant).

**Verified independently:**
- Ran both new test files (19 tests) on the branch — all pass.
- Reverted the touched source files to `main` while keeping the new tests — collection fails outright (`ImportError: cannot import name 'utc_now'`), confirming the fix is load-bearing, stronger evidence than the PR's own "11/13, 5/5 fail" claim.
- Ran the full `tests/export/ tests/ontology/ tests/provenance/` suite: 579 passed, 1 failure. That failure (`test_minted_entity_iri_is_stable_across_processes`) passes in isolation and — checked — fails identically on unmodified `main`, so it's pre-existing subprocess-test flakiness, not something this PR broke.
- Grepped `export/` and `provenance/` for any remaining naive `datetime.now()`/`datetime.utcnow()` call — none found.
- Confirmed `schemas.py`'s retained `datetime` import is still used elsewhere (`SourceReference.from_dict`), not dead code.
- All 10 CI checks pass.

**Design calls, all reasonable:** leaving the other 147 naive call sites for a separate migration (they compare against previously-stored naive data, so converting the write side alone would raise `TypeError`); `to_utc_datetime` returning `None` rather than raising on unparseable input, with both range-query methods falling back to the historical string comparison on an unreadable bound — verified by `test_an_unreadable_bound_falls_back_to_the_previous_behaviour`.

No changes requested.
